services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pnpm run dev:app"
    tty: true
    ports:
      - ${REACT_PORT}:5173
    environment:
      - VITE_PROXY_URL=${PROXY_URL}
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pnpm run dev:api"
    tty: true
    ports:
      - ${EXPRESS_PORT}:3000
    environment:
      - DB_HOST=db
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - CORS_URL=${CORS_URL}
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Tokyo
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
